version: '3.9'

services:

  db:
    image: postgres
#    restart: always
#    shm_size: 128mb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ttrice
volumes:
   postgres:
